#!/bin/sh

case "$1" in
    start)
        kill -9 `cat /var/www/zmq_broker/msg_broker.pid`
        python3 /var/www/zmq_broker/msg_broker.py &
    ;;
    stop)
        kill -9 `cat /var/www/zmq_broker/msg_broker.pid`
    ;;

esac

exit 0